name: Welcome comment

on:
  pull_request_target:
    types: [opened, labeled]

jobs:
  Welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            congrats ${{ github.repository_owner }}/${{ github.event.repository.name }}/tackle-ui nada
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ðŸ‘‹ Thanks for reporting! ${{ github.repository_owner }}/${{ github.event.repository.name }}/tackle-ui'
            })
          repo-token: ${{ secrets.GITHUB_TOKEN }}
